#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6648795963                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://drive.google.com/drive/folders/1zgJDh38_obuG_Z6zG4sxAfAFdO8TzMZv?usp=sharing                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Workouts App                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track your workouts and progress with Workouts App. Create personalized plans, log sets and reps, and hit your fitness goals. Simple, powerful, and always at your fingertips.



enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : # Evgenii Lebedev
your_link                                 : # https://twitter.com/nrlnishan
your_city                                 :
email_address                             : # gymdiaryios@gmail.com
facebook_username                         :
instagram_username                        : 
twitter_username                          : # gym_diary_ios
github_username                           : # nrlnishan
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Ready-made and custom workouts
    description                           : Choose from pre-built workout programs or create your own personalized routines.
    fontawesome_icon_name                 : dumbbell
    
  - title                                 : Workout calendar & stats
    description                           : Track your workouts with a detailed calendar and view a summary of your monthly progress.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : History
    description                           : Keep a comprehensive history of all your workouts, with exercise grouping for easy navigation.
    fontawesome_icon_name                 : history

  - title                                 : Exercise grouping
    description                           : Group your exercises for more efficient training sessions.
    fontawesome_icon_name                 : layer-group

  - title                                 : Rest timer with push notifications
    description                           : Stay on track with a rest timer that sends you push notifications when it’s time to get back to work.
    fontawesome_icon_name                 : clock
  
  - title                                 : Monthly summary
    description                           : Get a quick overview of your monthly achievements, including total workouts, weight lifted, and time spent training.
    fontawesome_icon_name                 : sync

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
